name: 'CI'
on:
  pull_request:
    types: [ closed ]
    branches:
      - master
  push:
    branches:
      - '**'
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
    - name: 'Checkout'
      uses: actions/checkout@v2
    - name: 'Set up Python'
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: 'Set up Poetry'
      uses: snok/install-poetry@v1
    - name: 'Install dependencies'
      run: poetry install --no-interaction --no-root
    - name: 'Run unit-tests'
      run: poetry run pytest

  coverage:
    runs-on: ubuntu-latest
    needs: tests
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - name: Coverage tests
        run: COVERALLS_REPO_TOKEN=${{ secrets.COVERALLS_TOKEN }} sh coverage.sh

  publish:
    if: github.ref == 'master'
    needs: coverage
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v2
      - name: 'Set up Python'
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: 'Set up Poetry'
        uses: snok/install-poetry@v1
      - name: 'Install dependencies'
        run: poetry install --no-interaction --no-root
      - name: 'Build version'
        run: poetry build
      - name: 'Publish version'
        run: poetry publish --username ${{ secrets.PYPI_USER }} --password ${{ secrets.PYPI_PASSWORD }}
